### ISSUE TITLE
Prod deployment

### ISSUE THREAD

**Issue by doerfli** [etherisc/flightdelay-ui#92]
# Tasks

- [x] create dokku app
- [x] configure dns
- [x] push image
- [x] config ready
- [x] apply config
- [x] cronjob
- [x] monitoring

## Config requirements

- [x] rpc node
- [x] application signer account funded
- [x] application signer min balance
- [x] oracle singer account funded
- [x] oracle signer min balance
- [x] token decided
